version: "3.8"
services:
  db:
    image: docker.io/library/postgres:alpine
    volumes:
      - database_data:/var/lib/postgresql/data
    command: -p ${DB_PORT:-5432}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_INITDB_ARGS=--locale=pt-BR
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

  app:
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DB_HOST=db
    depends_on:
      - db

  nginx:
    restart: always
    image: docker.io/library/nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx:/etc/nginx/conf.d:Z
    depends_on:
      - app
volumes:
  database_data: {}
